### ISSUE TITLE
GeoHuntsville Demo Task List

### ISSUE THREAD

**Issue by mikebotts** [opensensorhub/project-geohsv#19]
**City Hall Camera**
- [x] Get City Hall Camera connected - Mike
- [ ] Set up OSH node at Tim's (purchase, install, config) - Mike / Lee (waiting)
- [ ] Improve City Hall Camera setup (hardware) - Mike/Lee
- [x] City Hall Video Camera (config, calibration, etc.) - Lee / Mike
- [ ] Fix lag issue with PTZ tasking commands
- [x] Video Camera processing chain (existing process) ** - Alex/Lee
- [x] Video Camera processing chains (SensorML) - Alex
- [ ] Tipping and Cueing Demo - All
- [ ] Map view polygon to terrain AND buildings
- [ ] Drape video to terrain AND buildings
- [ ] Finish/Test Video Client - Lee (Waiting on process from Alex)

**Other Cameras**
- [x] ONVIF driver - Josh / Mike
- [ ] Finish testing ONVIF - Josh
- [ ] Pelco-D driver ?? - Josh / Mike
- [ ] VBC Cameras (Bosch fixed view and PTZ) - Josh / Mike
- [ ] Bosch 360 camera support with ePTZ
- [ ] PixPro SP-360 Camera (drone-only?) calibration - Lee
- [ ] Add motion alerts output
- [ ] Buy PTZ WiFi USB-powered video cameras
- [ ] Talk to VBC about installing our cameras (e.g. Axis PTZ on catwalk)
- [ ] Ask VBC about loaner 360 and PTZ cameras
- [ ] Talk to VBC about using their cameras on public network
- [x] Get VBC to open up outside connection to cameras

**Other Sensors**
- [x] other VBC sensors ??? - Josh
- [x] Door Hinge - Lee (Waiting on ZigBee Dongle)
- [x] Z-Wave (?)  - ??
- [x] Samsung SmartThings ??
- [x] Twitter Feed Driver - Josh
- [x] Simulated CBRNE Sensors (walking & hot zones) - Ian
- [ ] Robot ??
- [ ] Drone Tasking and Support - Alex
- [ ] Get UAV License (call Phil Owen - Energies) - Mike / Josh /  
- [ ] LampPost sensors (talk/work with GA Tech) - ??

**Other Sensors - Indoor location**
- [ ] WiFi Triangulation (Indoor Location) - Alex
- [x] UWB  driver (Indoor Location) - Josh
- [ ] RFID badge tracking - ??
- [ ] Cell Phone (Bluetooth Beacon) - used to spatially guide or inform during emergency

**Clients**
- [x] WFS Draw Layer in Client - Mathieu
- [ ] Test DrawLayer and drone geolocation on Android Tablet
- [x] Location Source UI - Lee
- [ ] Field Deployment App - ??
- [ ] Client Toolkit Issues and Extensions - Mathieu
- [ ] Common Operating Picture client - ??
- [ ] GeoQ Integration ?
- [ ] MAGE ??

**Execution**
- [ ] Drone Practice (July)
- [ ] City Hall Camera Practice (Aug)
- [ ] VBC Practice (July)
- [ ] Off-Site Practice (End of July)
- [ ] VBC Indoor Practice (Begin June)
- [ ] On-Site Practice (End of July)
- [ ] Demo (End of August)
